config/routes.rb
Rails.application.routes.draw do  
  resources :jinetes
  get '/about'    => 'high_voltage/pages#show', id: 'about'
  get '/contact'  => 'high_voltage/pages#show', id: 'contact'
  get '/privacy'  => 'high_voltage/pages#show', id: 'privacy'
  get '/terms'    => 'high_voltage/pages#show', id: 'terms'

  get '/home', to: redirect('/')

  root :to => 'high_voltage/pages#show', id: 'home'

end

app/models/jinete.rb
class Jinete
  include Mongoid::Document
  field :nombre, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jinetes_controller.rb
class JinetesController < ApplicationController
  before_action :set_jinete, only: [:show, :edit, :update, :destroy]

  # GET /jinetes
  # GET /jinetes.json
  def index
    @jinetes = Jinete.all
  end

  # GET /jinetes/1
  # GET /jinetes/1.json
  def show
  end

  # GET /jinetes/new
  def new
    @jinete = Jinete.new
  end

  # GET /jinetes/1/edit
  def edit
  end

  # POST /jinetes
  # POST /jinetes.json
  def create
    @jinete = Jinete.new(jinete_params)

    respond_to do |format|
      if @jinete.save
        format.html { redirect_to @jinete, notice: 'Jinete was successfully created.' }
        format.json { render :show, status: :created, location: @jinete }
      else
        format.html { render :new }
        format.json { render json: @jinete.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jinetes/1
  # PATCH/PUT /jinetes/1.json
  def update
    respond_to do |format|
      if @jinete.update(jinete_params)
        format.html { redirect_to @jinete, notice: 'Jinete was successfully updated.' }
        format.json { render :show, status: :ok, location: @jinete }
      else
        format.html { render :edit }
        format.json { render json: @jinete.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jinetes/1
  # DELETE /jinetes/1.json
  def destroy
    @jinete.destroy
    respond_to do |format|
      format.html { redirect_to jinetes_url, notice: 'Jinete was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jinete
      @jinete = Jinete.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jinete_params
      params.require(:jinete).permit(:nombre)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def site_name
    # Change the value below between the quotes.
    "club hipico"
  end

  def site_url
    if Rails.env.production?
      # Place your production URL in the quotes below
      "http://heroke.clubhipico.com/"
    else
      # Our dev & test URL
      "http://localhost:3000"
    end
  end

  def meta_author
    # Change the value below between the quotes.
    "Ivan Marincovich"
  end

  def meta_description
    # Change the value below between the quotes.
    "Guardar resultados de carreras de caballos en chile"
  end

  def meta_keywords
    # Change the value below between the quotes.
    "Francisco Marincovich Lizama"
  end

  # Returns the full title on a per-page basis.
  # No need to change any of this we set page_title and site_name elsewhere.
  def full_title(page_title)
    if page_title.empty?
      site_name
    else
      "#{page_title} | #{site_name}"
    end
  end

end

app/helpers/jinetes_helper.rb
module JinetesHelper
end

app/views/jinetes/_form.html.erb
<%= form_for(@jinete) do |f| %>
  <% if @jinete.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@jinete.errors.count, "error") %> prohibited this jinete from being saved:</h2>

      <ul>
      <% @jinete.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jinetes/edit.html.erb
<h1>Editing jinete</h1>

<%= render 'form' %>

<%= link_to 'Show', @jinete %> |
<%= link_to 'Back', jinetes_path %>

app/views/jinetes/index.html.erb
<% provide(:title, 'Lista de Jinetes') %>

<h1>Lista de  Jinetes</h1><br>
<%= link_to 'Agregar Jinete', new_jinete_path ,class: "btn btn-large btn-primary"%><br>

<div class="container"> 
  <br><div class="row">     
    <table class="table table-striped table-bordered table-condensed table-hover">
      <thead>
        <tr>
          <th>Nombre</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @jinetes.each do |jinete| %>
          <tr>
            <td><%= jinete.nombre %></td>
            <td><%= link_to '<i class="fa fa-pencil"></i>  Editar'.html_safe, edit_jinete_path(jinete) %></td>
            <td><%= link_to '<i class="fa fa-trash-o"></i>  Borrar'.html_safe, jinete, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    
  </div>
</div>

app/views/jinetes/new.html.erb
<h1>New jinete</h1>

<%= render 'form' %>

<%= link_to 'Back', jinetes_path,class: "btn btn-large btn-default" %>

app/views/jinetes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @jinete.nombre %>
</p>

<%= link_to 'Edit', edit_jinete_path(@jinete) %> |
<%= link_to 'Back', jinetes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="<%= meta_description %>">
  <meta name="author" content="<%= meta_author %>">
  <meta name="Keywords" content="<%= meta_keywords %>">

  <title><%= full_title(yield(:title)) %></title>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
  <a href="#Top"></a>
</head>
<body>
  <div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to site_name, site_url, :class => "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav pull-right">
          <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
          <li class="<%= 'active' if current_page?(jinetes_path) %>"><%= link_to "Jinetes", jinetes_path %></li>
        </ul>
      </div><!-- /.nav-collapse -->
    </div><!-- /.container -->
  </div><!-- /.navbar -->
  <% if current_page?(root_path) %>
    <% if content_for?(:jumbotron) %>
      <div class="jumbotron">
        <div class="container">
          <%= yield :jumbotron %>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="container">
  <% end %>
  <%= yield %>
  <footer>
    <hr>
      <p class="pull-right">
        <%= link_to '<span class="glyphicon-class glyphicon glyphicon-chevron-up"></span> Back to top'.html_safe, '#Top' %>
      </p>
      <p>
        &copy; <%= Time.now.year %> <%= site_name %> 
        &bull;
        <%= link_to "Privacy", privacy_path %></li>
        &bull;
        <%= link_to "Terms", terms_path %></li>
      </p>
    </footer>
  </div> <!-- /container -->
</body>
</html>